# Operations mode = {GBAFS, Full-GBAFS, CS, Full-CS}
operation_mode: Full-CS

data:
  path: ./app/datasets/cardiotocography.csv
  split_ratio: 75-25
  label_column_name: class

cross_validation:
  num_splits: 2
  allow_shuffle: true

tsne_algorithm:
  iterations: 1000
  perplexity_value: 15

constraint_satisfaction:
  budget: 5