# Operations mode = {GB_AFS,   Full-GB_AFS,
#                    GB_BC_FS, Full-GB_BC_FS}
operation_mode: Full-CS

data:
  path: ./app/datasets/cardiotocography.csv
  split_ratio: 75-25
  label_column_name: class

cross_validation:
  num_splits: 2
  allow_shuffle: true

tsne_algorithm:
  iterations: 1000
  perplexity_value: 15

budget_constraint:
  budget: 5
  generate_costs: true
  cost_column_name: cost