operation_mode: full

visualization_plots:
  tsne_plot_enabled: true
  cluster_plot_enabled: true
  silhouette_plot_enabled: true
  jm_cluster_plot_enabled: true
  cost_to_silhouette_enabled: true
  accuracy_to_silhouette_enabled: true

data:
  path: ./app/datasets/cardiotocography.csv
  split_ratio: 75-25
  label_column_name: class

cross_validation:
  num_splits: 2
  allow_shuffle: true

tsne_algorithm:
  iterations: 1000
  perplexity_value: 15

constraint_satisfaction:
  budget: 5