operation_mode: full

visualization_plots:
  tsne_plot_enabled: true
  silhouette_plot_enabled: true
  cluster_plot_enabled: true
  clustering_based_jm_enabled: true
  accuracy_to_silhouette_enabled: true

data:
  path: ./lib/common/datasets/cardiotocography.csv
  split_ratio: 75-25
  label_column_name: class

cross_validation:
  num_splits: 2
  allow_shuffle: true

tsne_algorithm:
  iterations: 1000
  perplexity_value: 15

k_medoids_clustering:
  algorithm_method: pam
